### ISSUE TITLE
Não gera arquivo no final

### ISSUE THREAD

**Issue by momseum** [LucasIME/filmow2letterboxd#1]
Olá Lucas, sou novo no GitHub e entrei mais para saber se pode me ajudar com um erro que está dando no programa para Mac: ele não gera nenhum arquivo no final e me dá um erro "Fetching links from Page https://filmow.com/usuario/momseum
/filmes/quero-ver/?pagina=4
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/filmowclient.rs:115:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/filmowclient.rs:169:25"

Consegue me ajudar a resolver isso? 

Obrigado.

**Comment by LucasIME** [comment]
Opa, @momseum, tudo bem?

Tentei rodar aqui o programa para o seu usário e de fato dá um erro. Aparentemente [esse filme](https://filmow.com/jesus-no-mundo-maravilha-e-outras-historias-da-policia-brasileira-t19490/) que ele tenta buscar na 4a página da sua lista de `quero-ver` está sem a data de lançamento.

O que posso fazer por enquanto é fazer o programa ignorar esse filme e continuar a execução. E quando tiver um pouco mais de tempo conserto o código de maneira que consiga identificar o filme mesmo sem a data de lançamento.

Te aviso por aqui quando tiver consertado.

**Comment by LucasIME** [comment]
Dei release agora na versão [0.2.3](https://github.com/LucasIME/filmow2letterboxd/releases/tag/0.2.3), que deve resolver o seu problema. Por enquanto ela vai ignorar o filmes que não conseguir achar, mas devem ser poucos. Me avisa se não conseguir rodar com a versão nova.

**Comment by momseum** [comment]
Lucas, muitíssimo obrigado, fazia algum tempo que eu buscava alguma ferramenta que conseguisse exportar minha lista de Quero Ver do Filmow para o Letterboxd, que para mim é tão ou até mais importante do que a lista de filmes já visto. Agradeço enormemente.
