### ISSUE TITLE
Exportar avaliação

### ISSUE THREAD

**Issue by leonardoaranha-git** [LucasIME/filmow2letterboxd#2]
Olá, o programa funciona muito bem.
Porém queria saber se tem como exportar a avaliação também, ia ser muito útil.
Obrigado!

**Comment by LucasIME** [comment]
Olá, littl3viking.

Exist como fazer sim, o único problema é que teria que mudar consideravelmente a arquitetura atual do programa. Ele sempre tentar pegar as informações da pagina do filme (ex: https://filmow.com/o-poco-t284145/). Só que para pegar a avaliação por essa página, teria que estar logado como o usuário, o que não gostaria de fazer por motivos de segurança. A outra maneira que tem de pegar a nota, é diretamente pela pagina de ["Já vi"](https://filmow.com/usuario/lucasmeireles33/filmes/ja-vi/). Mas para isso preciso mudar um pouco a arquitetura do programa, para conseguir extrair informações dessa pagina também. Vou tentar implementar quando tiver um pouco de tempo livre.

**Comment by LucasIME** [comment]
Só tirando uma dúvida, @littl3viking : Quando você diz "avaliação", você quer dizer a nota (0 a 5) do filme? Ou o review que você escreveu sobre ele?

**Comment by leonardoaranha-git** [comment]
> 
> 
> Só tirando uma dúvida, @littl3viking : Quando você diz "avaliação", você quer dizer a nota (0 a 5) do filme? Ou o review que você escreveu sobre ele?

Sim, a nota.
Caso não tenha como fazer, não tem problema.
O programa já está excelente, é mais rápido que os outros que existem.
:)

**Comment by LucasIME** [comment]
Eu comecei a fazer umas mudanças aqui para conseguir. Já consegui pegar a nota, mas não curti muito como o código ficou. Devo dar uma refatorada nos próximos dias e lanço uma versão nova com essa funcionalidade.

**Comment by LucasIME** [comment]
@littl3viking, acabei de dar release na versão `0.3.1` que deve conseguir exportar as suas avaliações também: https://github.com/LucasIME/filmow2letterboxd/releases/tag/0.3.1

Me avise se não funcionar!

**Comment by leonardoaranha-git** [comment]
> 
> 
> @littl3viking, acabei de dar release na versão `0.3.1` que deve conseguir exportar as suas avaliações também: https://github.com/LucasIME/filmow2letterboxd/releases/tag/0.3.1
> 
> Me avise se não funcionar!

Acabei de testar e funcionou perfeitamente.
Agradeço muito!
