### ISSUE TITLE
meu windows 32 bit não rodou o aplicativo

### ISSUE THREAD

**Issue by diegooliveiralima** [LucasIME/filmow2letterboxd#5]
Existe uma versão compatível com sistemas 32 bit?

**Comment by LucasIME** [comment]
Não tem disponível na seção de downloads, mas tem como compilar uma versão compatível sim.

Vou tentar adicionar versões 32 bit na página de downloads em breve.

**Comment by diegooliveiralima** [comment]
ebaa. Achei interessante que tua versão passa as notas dos filmes também né, acho que dos outros que fizeram antes não tem isso. Vou aguardar, obrigado!

**Comment by LucasIME** [comment]
@diegooliveiralima , acabei de fazer uma release nova, [0.3.2](https://github.com/LucasIME/filmow2letterboxd/releases/tag/0.3.2), que deve ter o [arquivo de 32 bits](https://github.com/LucasIME/filmow2letterboxd/releases/download/0.3.2/filmow2letterboxd-0.3.2-i686-pc-windows-gnu.zip) (filmow2letterboxd-0.3.2-i686-pc-windows-gnu.zip) para baixar. Me avisa se não funcionar!

**Comment by diegooliveiralima** [comment]
Rodou!! Adicionou 900 dos 1200 filmes, acho que é por causa dos brasileiros né? Não sei. Mas deu certo obrigado!

**Comment by LucasIME** [comment]
Estranho, normalmente a taxa de falha não é tão alta. Me manda o seu perfil do filmow pra eu dar uma olhada e testar o que tem de errado?

**Comment by diegooliveiralima** [comment]
https://filmow.com/usuario/userdiegooli

https://letterboxd.com/diegooli/

Com uma amiga também deu o mesmo de falha, 1988/1708

**Comment by LucasIME** [comment]
Hm... Estranho. Parece que o próprio Filmow é incosistente com a contagem. Em uma parte do seu perfil aparece o número 1238 
![image](https://user-images.githubusercontent.com/6787311/83966108-177d0080-a8b0-11ea-9729-da8017db4557.png)

Mas em outra parte, aparece que são só 930 filmes assistidos: 
![image](https://user-images.githubusercontent.com/6787311/83966123-2a8fd080-a8b0-11ea-8dad-6da93721e11d.png)

Eu acho é que no seu perfil você tem bastante coisa categorizada como `Curta`, `Séries` e `TV`. O meu programa por enquanto só consegue migrar o que está na categoria `Filmes`. Então, provavelmente ele só achou 900 dos seus 930 filmes. Vou ver o quão dificiil seria adicionar a categoria de Curtas e Séries também.

**Comment by LucasIME** [comment]
Acho que consegui aqui. Testei com o seu perfil e dessa vez consegui 336  `filmes que quero ver` e 1202 `filmes assistido`. Ainda não são todos que você tem, mas é bem mais próximo do total. Vou lançar uma versão nova com a correção.

**Comment by LucasIME** [comment]
@diegooliveiralima  Pode tentar a [release nova 0.4.0](https://github.com/LucasIME/filmow2letterboxd/releases/tag/0.4.0) e ver se funciona para você?

**Comment by diegooliveiralima** [comment]
Agora deu 1045 assistidos e 312 em quero assistir, devem ser todos agora! O resto deve ser séries, tinha esquecido que não tem séries no letterbox (175 séries que não foram + 1045 que já tem = 1220)

![image](https://user-images.githubusercontent.com/3311203/83969451-8190a800-a8a6-11ea-933a-21f2efaf613f.png)


Já tá bem eficaz, vou publicar sua aplicação em grupos de cinema do facebook e fóruns para divulgar ok?

Obrigado!

**Comment by LucasIME** [comment]
Muito obrigado, Diego! Me avise se tiver algum outro problema!
