### ISSUE TITLE
Primeira vez rodando no Linux

### ISSUE THREAD

**Issue by geraldohomero** [LucasIME/filmow2letterboxd#9]
A primeira tentativa pegou somente 190. Rodando mais uma vez deu certo. Não apareceu nenhuma mensagem de erro nem nada

**Comment by LucasIME** [comment]
Obrigado pelo report, Geraldo! Você pode me mandar o link do seu perfil no filmow para eu tentar reproduzir o erro e ver o que está acontecendo?

**Comment by geraldohomero** [comment]
Claro!! https://filmow.com/usuario/geraldohomero

**Comment by LucasIME** [comment]
Hm... não consegui reproduzir o erro rodando localmente aqui. Ele pega todos quase todos os filmes que voce ja viu e a watchlist de boa.

Dado que você tem background de programação, conseguiria tentar rodar o projeto pelo codigo fonte para ver que erro que rola para você? Você precisaria instalar o compilado e package manager de Rust e rodar `cargo run geraldohomero`

**Comment by LucasIME** [comment]
Deixando aqui os arquivos criados quando rodei localmente para você poder agilizar sua migração  enquanto isso:
[watchlist.csv](https://github.com/LucasIME/filmow2letterboxd/files/13933360/watchlist.csv)
[watched.csv](https://github.com/LucasIME/filmow2letterboxd/files/13933361/watched.csv)

**Comment by geraldohomero** [comment]
Eu já consegui pegar todos quando fiz pela segunda vez, mas muito obrigado!!! Só abri essa issue caso algo semelhante aconteça com mais alguém! 

Tentei novamente agora e aconteceu algo parecido, pegou somente mil e poucos no arquivo .csv. 
Não tinha reparado algum erro da vez que pegou somente 190, mas aqui está o que apareceu agora:
Depois de vários `Could not construct movie from url`,  `Error was: Failed to get HTML for url` e `Received error: reqwest::Error { kind: Request, url: "https://filmow.com/under-the-dome-prisao-invisivel-1a-temporada-t70032/", source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 101, kind: Other, message: "Network is unreachable" })) }`

Finalmente: 

```
Failed to get html for url https://filmow.com/usuario/geraldohomero
/ja-vi/?pagina=81. Error: Failed to get HTML for url: https://filmow.com/usuario/geraldohomero
/ja-vi/?pagina=81. Received error: reqwest::Error { kind: Request, url: "https://filmow.com/usuario/geraldohomero/ja-vi/?pagina=81", source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 101, kind: Other, message: "Network is unreachable" })) }
Successfully generated watched movies file: watched.csv
Filmow2letterboxed has finished importing your Filmow profile! You should be able to find .csv files in the same directory of the executable. For more instructions on how to import these files to letterboxd, go to https://github.com/LucasIME/filmow2letterboxd
``` 

Esses foram os arquivos: 
[watched.csv](https://github.com/LucasIME/filmow2letterboxd/files/13933394/watched.csv)
[watchlist.csv](https://github.com/LucasIME/filmow2letterboxd/files/13933395/watchlist.csv)
[output.txt](https://github.com/LucasIME/filmow2letterboxd/files/13933431/output.txt) completo do terminal

Poderia ser o Filmow sobrecarregado? A minha conexão permaneceu estável durante todo o processo!

**Comment by LucasIME** [comment]
Eu imagino que deva ser algum tipo de rate limiting ou proteção de DoS pelo lado do Filmow que quebre alguma dessas requests por serem muitas num espaço curto de tempo. Mas eu esperaria que eles respondessem com algum codigo http 429 pelo menos. 

Enfim, tenho que atualizar o programa para ter alguma forma de retry em caso de erro de rede e deixar isso claro no output.

**Comment by LucasIME** [comment]
Adicionei a logica de try nessa última release [0.8.0](https://github.com/LucasIME/filmow2letterboxd/releases/tag/0.8.0), altém de paralelizar a requisição das páginas, então também deve estar rodando um pouco mais rápido.

Me avisa se ainda tiver com o mesmo problema!
